<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AiUsageMonitor.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiUsageMonitor.Domain\AiUsageMonitor.Domain.csproj" />
  </ItemGroup>

</Project>
